// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQMXP3PIDD9J7CMwRBGKwF0dp02ETmt-U',
    appId: '1:525421350622:web:92afb93558ebcde70c3c4f',
    messagingSenderId: '525421350622',
    projectId: 'subscripto-1a42e',
    authDomain: 'subscripto-1a42e.firebaseapp.com',
    storageBucket: 'subscripto-1a42e.firebasestorage.app',
    measurementId: 'G-YDV9EH81YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVHz9T3lJkXBDkVIDyupZ48H6244JoKX4',
    appId: '1:525421350622:android:9af5ca5e2082611c0c3c4f',
    messagingSenderId: '525421350622',
    projectId: 'subscripto-1a42e',
    storageBucket: 'subscripto-1a42e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDHOBU7ckGlMt366X3PU7WiukEA869rUA',
    appId: '1:525421350622:ios:b699455e0480b14c0c3c4f',
    messagingSenderId: '525421350622',
    projectId: 'subscripto-1a42e',
    storageBucket: 'subscripto-1a42e.firebasestorage.app',
    iosBundleId: 'com.example.subscripto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDHOBU7ckGlMt366X3PU7WiukEA869rUA',
    appId: '1:525421350622:ios:b699455e0480b14c0c3c4f',
    messagingSenderId: '525421350622',
    projectId: 'subscripto-1a42e',
    storageBucket: 'subscripto-1a42e.firebasestorage.app',
    iosBundleId: 'com.example.subscripto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQMXP3PIDD9J7CMwRBGKwF0dp02ETmt-U',
    appId: '1:525421350622:web:0211b2988c9ca6b90c3c4f',
    messagingSenderId: '525421350622',
    projectId: 'subscripto-1a42e',
    authDomain: 'subscripto-1a42e.firebaseapp.com',
    storageBucket: 'subscripto-1a42e.firebasestorage.app',
    measurementId: 'G-EMCZEKENSN',
  );
}
