// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQK2Epd7RbBEJIMaVHGPZVkvT9DvAffbY',
    appId: '1:541182987526:web:2d95f9ca1d73717cd2a287',
    messagingSenderId: '541182987526',
    projectId: 'taskmaster-66110',
    authDomain: 'taskmaster-66110.firebaseapp.com',
    storageBucket: 'taskmaster-66110.appspot.com',
    measurementId: 'G-G3XXBQG7G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR64vgW0CR0T1CeNyHK5fx32J9Cbz6lGw',
    appId: '1:541182987526:android:57cb1803baa924e5d2a287',
    messagingSenderId: '541182987526',
    projectId: 'taskmaster-66110',
    storageBucket: 'taskmaster-66110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASXkoGnwYiqjXLQlzlwGEMb8MBPs8CW5I',
    appId: '1:541182987526:ios:7bd27aa05220622dd2a287',
    messagingSenderId: '541182987526',
    projectId: 'taskmaster-66110',
    storageBucket: 'taskmaster-66110.appspot.com',
    iosBundleId: 'com.example.mainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASXkoGnwYiqjXLQlzlwGEMb8MBPs8CW5I',
    appId: '1:541182987526:ios:55cfed31b84b7329d2a287',
    messagingSenderId: '541182987526',
    projectId: 'taskmaster-66110',
    storageBucket: 'taskmaster-66110.appspot.com',
    iosBundleId: 'com.example.mainApp.RunnerTests',
  );
}
